server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.232.130
aliyun:
  sms:
    accessKeyId: LTAIZWwZTMwfbDDf
    accessKeySecret: 5VENiliqIFzzLB4qcSq8VHRGojraGL
    template_code: SMS_165414716
    sign_name: 乐优商城